import { NextStep } from "@/components/next-step";
import { estimateTotal, scopeVersion } from "@/lib/workflow";
import Link from "next/link";
import { projectData } from "@/lib/queries";
import { Card, Field, Textarea } from "@/components/ui";
import { MutationForm } from "@/components/form";
import { dateLabel, won } from "@/lib/model";
export default async function Overview({ params }: { params: Promise<{ projectId: string }> }) {
  const {projectId} = await params; const d = await projectData(projectId); const locked = d.ctx.role !== "OWNER" || ["COMPLETED", "CANCELLED"].includes(d.project.status) || d.scopes.some(s => ["APPROVED", "WAITING_APPROVAL"].includes(s.status));
  return <div className="stack"><NextStep project={d.project} /><div className="two-col"><div className="stack"><Card title="고객의 첫 요청" hint="원문의 의도부터 이해하는 것이 좋은 시작입니다."><div className="card-body"><p className="prose">{d.initial?.content}</p>{!locked && <details><summary>원문 수정</summary><MutationForm action="initial.save" payload={{projectId}}><Textarea name="content" label="고객 원문" value={d.initial?.content} required /></MutationForm></details>}<div className="actions-row"><Link className="button secondary" href={`/projects/${projectId}/requirements`}>요구사항 정리하기 →</Link></div></div></Card><Card title="고객 피드백"><div className="card-body">{d.feedback.length ? d.feedback.map(f => <div key={f.id} className="activity-item"><div><strong>{f.name} · {{ APPROVE: "승인", REVISE: "수정 요청", REJECT: "거절" }[f.decision] || "검토 의견"}</strong><p className="prose">{f.message}</p><small>{dateLabel(f.createdAt)}</small></div></div>) : <p className="text-xs">고객의 답변과 수정 요청이 여기에 기록됩니다.</p>}</div></Card></div><div className="stack"><Card title="프로젝트 정보"><div className="card-body"><dl className="info-grid"><div><dt>고객</dt><dd><Link className="inline-link" href={`/clients/${d.client.id}`}>{d.client.company || d.client.name}</Link></dd></div><div><dt>담당자</dt><dd>{d.client.name}</dd></div><div><dt>견적</dt><dd>{estimateTotal(d.project) == null ? "미정" : won(estimateTotal(d.project)!)}</dd></div><div><dt>희망 완료일</dt><dd>{dateLabel(d.project.deadline)}</dd></div><div><dt>요구사항</dt><dd>{d.requirements.length}개</dd></div><div><dt>현재 Scope</dt><dd>{d.scopes[0] ? scopeVersion(d.scopes[0]) : "아직 없음"}</dd></div></dl>{d.project.referenceUrl && <p className="mt-5"><a className="inline-link" href={d.project.referenceUrl} target="_blank" rel="noreferrer">참고 사이트 ↗</a></p>}{d.project.notes && <p className="prose mt-5">{d.project.notes}</p>}</div></Card>
  {d.ctx.role === "OWNER" && <Card title="프로젝트 관리"><div className="card-body">{!locked && <details><summary>기본 정보 수정</summary><MutationForm action="project.update" payload={{projectId, clientId:d.client.id}}><Field label="프로젝트 이름" name="name" value={d.project.name} required /><Field label="예산" name="budget" type="number" min={0} value={d.project.budget} /><Field label="희망 완료일" name="deadline" type="date" value={d.project.deadline} /><Field label="참고 URL" name="referenceUrl" value={d.project.referenceUrl} /><Textarea label="메모" name="notes" value={d.project.notes} /></MutationForm></details>}<MutationForm action="project.status" payload={{projectId}} submit="상태 변경"><label>진행 상태<select name="status" required defaultValue={["ACTIVE", "COMPLETED", "CANCELLED"].includes(d.project.status) ? d.project.status : ""}><option value="" disabled>변경할 상태 선택</option><option value="COMPLETED">완료</option><option value="CANCELLED">취소</option><option value="ACTIVE">진행 중</option></select></label></MutationForm>{!d.scopes.length && <div className="actions-row"><MutationForm className="compact" action="project.delete" payload={{projectId}} submit="프로젝트 삭제" variant="danger" confirm="프로젝트를 삭제할까요? 목록에서 사라지며 되돌릴 수 없습니다." /></div>}</div></Card>}</div></div><Card title="최근 변경 요청"><div className="card-body">{d.changes.length ? d.changes.slice(0,3).map(c => <p key={c.id}><Link className="inline-link" href={`/projects/${projectId}/changes#${c.id}`}>CR #{c.number} · {c.request.slice(0,70)}</Link></p>) : <p>추가 요청이 생기면 기존 Scope와 비교해 별도로 승인받으세요.</p>}</div></Card></div>;
}
