import { ProjectState } from "@/components/next-step";
import Link from "next/link";
import { projectData } from "@/lib/queries";
import { Card, Field, Textarea, Empty } from "@/components/ui";
import { MutationForm } from "@/components/form";
import { ScopeDocument } from "@/components/scope-document";
import { dateLabel } from "@/lib/model";
export default async function Scope({params,searchParams}: {params:Promise<{projectId:string}>;searchParams:Promise<{version?:string}>}) {
  const {projectId} = await params; const d = await projectData(projectId); const {version} = await searchParams; const scope = d.scopes.find(s=>s.id===version) || d.scopes[0];
  const owner = d.ctx.role === "OWNER"; const closed = ["COMPLETED", "CANCELLED"].includes(d.project.status);
  const editable = owner && !closed && !d.scopes.some(s=>["APPROVED","WAITING_APPROVAL"].includes(s.status)); const content = scope?.document;
  const issues = [!d.requirements.some(r => r.status === "CONFIRMED") && "확정 요구사항", d.requirements.some(r => r.status === "PENDING") && "확인 필요 요구사항 정리", d.questions.some(q => !q.answer) && "고객 질문 답변", (!d.estimate || d.requirements.filter(r => r.status === "CONFIRMED").some(r => !d.items.some(i => i.requirementId === r.id && i.reviewed))) && "모든 요구사항 견적 검토", scope && scope.basedOnRevision !== d.project.revision && "변경된 내용으로 초안 다시 저장", scope && !scope.document.durationDays && "예상 기간"].filter(Boolean);
  return <div className="stack"><ProjectState project={d.project} />{d.scopes.length > 0 && <div className="row"><div className="actions-row" style={{margin:0}}>{d.scopes.map(s=><Link className="button small secondary" aria-current={s.id === scope?.id ? "page" : undefined} href={`?version=${s.id}`} key={s.id}>{`v${s.version} ${s.status === "APPROVED" ? "승인" : s.status === "WAITING_APPROVAL" ? "승인 대기" : "초안"}`}</Link>)}</div><span className="text-xs muted">승인된 버전은 원본 그대로 보관됩니다.</span></div>}
  {owner && !closed && scope && ["DRAFT", "WAITING_APPROVAL"].includes(scope.status) && <Card title={scope.status === "WAITING_APPROVAL" ? "고객 승인 대기" : "고객 승인 요청"} hint="문서와 견적을 미리 확인해주세요. 발급된 링크는 7일간 유효합니다."><div className="card-body">{issues.length > 0 && <div className="form-error"><strong>승인 요청 전 확인할 항목</strong><ul>{issues.map(issue => <li key={String(issue)}>{issue}</li>)}</ul><Link href={`/projects/${projectId}/estimate`}>요구사항·견적 확인 →</Link></div>}<div className="actions-row"><a className="button secondary" href="#preview">문서 미리보기</a><MutationForm variant="primary" action="share.create" payload={{projectId,purpose:"SCOPE",targetId:scope.id}} disabled={issues.length > 0} submit={scope.status === "WAITING_APPROVAL" ? "승인 링크 재발급" : "고객 승인 요청 · 링크 발급"} /></div>{scope.status === "WAITING_APPROVAL" && <div className="actions-row"><MutationForm action="scope.withdraw" payload={{ projectId, scopeId: scope.id }} submit="승인 요청 회수 · 초안 수정" confirm="공유한 승인 링크를 회수하고 초안으로 되돌릴까요?" /></div>}</div></Card>}
  <div id="preview">{scope && <ScopeDocument document={scope.document} version={scope.version} status={scope.status} approvedAt={scope.approvedAt} approvedBy={scope.approvedBy} />}</div>
  {editable && <Card title={scope ? "Scope 초안 수정" : "Scope 초안 만들기"} hint="요구사항과 최신 견적을 문서에 반영합니다."><div className="card-body"><MutationForm key={scope?.id} variant={scope ? "secondary" : "primary"} action={scope ? "scope.edit" : "scope.create"} payload={{projectId,...(scope ? {scopeId:scope.id} : {})}} submit={scope ? "초안 저장 · 최신 견적 반영" : "Scope 초안 생성"}><Textarea label="프로젝트 설명" name="description" value={content?.description || d.initial?.content} required /><div className="form-grid"><Textarea label="제외 범위 (한 줄에 하나씩)" name="excluded" value={content?.excluded.join("\n") || "명시되지 않은 추가 기능\n외부 서비스 이용료"} /><Textarea label="가정 및 협의 사항 (한 줄에 하나씩)" name="assumptions" value={content?.assumptions.join("\n") || "고객이 콘텐츠와 브랜드 자료를 제공합니다.\n세금 및 외부 서비스 비용은 별도 협의합니다."} /><Textarea label="외부 연동 (한 줄에 하나씩)" name="integrations" value={content?.integrations.join("\n")} /><Textarea label="납품 범위 (한 줄에 하나씩)" name="deliverables" value={content?.deliverables.join("\n") || "서비스 소스 코드\n운영 환경 배포\n기본 운영 가이드"} required /><Field label="예상 개발 기간 (일)" name="durationDays" type="number" value={scope?.document.durationDays || 30} min={1} max={3650} required /></div></MutationForm></div></Card>}
  {scope?.status==="APPROVED" && <div className="notice"><span>이 버전은 고객이 승인했습니다. 새로운 범위는 변경 요청을 통해 합의하세요.</span><Link className="button" href={`/projects/${projectId}/changes#new`}>새 변경 요청 →</Link></div>}
  {owner && d.tokens.length > 0 && <Card title="공유 링크 관리"><div className="table-wrap"><table><thead><tr><th>용도</th><th>만료일</th><th>상태</th><th>관리</th></tr></thead><tbody>{d.tokens.map(t=><tr key={t.id}><td>{t.purpose==="QUESTIONS" ? "질문 답변" : t.purpose==="SCOPE" ? "Scope 승인" : "변경 승인"}</td><td>{dateLabel(t.expiresAt)}</td><td>{t.revokedAt ? "회수됨" : new Date(t.expiresAt) < new Date() ? "만료됨" : t._count?.feedback ? "처리 완료 · 결과 조회" : "사용 가능"}</td><td>{!t.revokedAt && <MutationForm className="compact" variant="danger" confirm="이 링크를 폐기할까요?" action="share.revoke" payload={{projectId,tokenId:t.id}} submit="링크 폐기" />}</td></tr>)}</tbody></table></div></Card>}
  {!scope && !editable && <Empty title="아직 Scope가 없습니다" description="요구사항과 견적을 먼저 정리해주세요." />}</div>;
}
