"use client";
import { useState } from "react";
import { initialSchema, questionsSchema, requirementsSchema, workSchema, roles, roleLabels, labels, type RequirementInput } from "@/lib/model";
import type { AIDraft } from "@/lib/queries";
import { MutationForm } from "./form";
import { AIButton } from "./ai";

const schemas = { initial: initialSchema, questions: questionsSchema, requirements: requirementsSchema, estimate: workSchema };
type Task = keyof typeof schemas;
function Feature({ value, onChange }: { value: RequirementInput; onChange: (value: RequirementInput) => void }) {
  return <div className="form-grid">{(["title", "category", "description"] as const).map(key => <label key={key} className={key === "description" ? "wide" : ""}>{{ title: "기능 이름", category: "분류", description: "완료 기준" }[key]}<textarea required value={value[key]} onChange={e => onChange({ ...value, [key]: e.target.value })} rows={2} /></label>)}<label>유형<select value={value.type} onChange={e => onChange({ ...value, type: e.target.value as RequirementInput["type"] })}>{["FEATURE","NON_FUNCTIONAL","DESIGN","INFRA","EXTERNAL_INTEGRATION"].map(v => <option key={v} value={v}>{labels[v]}</option>)}</select></label><label>우선순위<select value={value.priority} onChange={e => onChange({ ...value, priority: e.target.value as RequirementInput["priority"] })}>{["HIGH","MEDIUM","LOW"].map(v => <option key={v} value={v}>{labels[v]}</option>)}</select></label></div>;
}
export function AIReview({ projectId, task, draft, revision, requirements = [], replaces = false }: { projectId: string; task: Task; draft: AIDraft; revision: number; requirements?: { id: string; title: string }[]; replaces?: boolean }) {
  const parsed = schemas[task].safeParse(draft.result);
  const [result, setResult] = useState(parsed.success ? parsed.data : null);
  if (!result) return <p role="alert">분석 결과를 표시할 수 없습니다. 다시 생성해주세요.</p>;
  if (draft.revision !== revision) return <div className="notice"><span>입력이 변경되어 이전 AI 결과는 반영할 수 없습니다. 새로 분석해주세요.</span><AIButton projectId={projectId} task={task} force /></div>;
  return <section className="card"><div className="card-heading"><div><h2>AI {labels[task]} · 검토 초안</h2><p>아직 반영되지 않았습니다. 내용을 수정한 뒤 확인해주세요.</p></div></div><div className="card-body"><MutationForm action="ai.apply" payload={{ projectId, task, revision: draft.revision }} submit="검토 완료 · 반영" variant="primary" confirm={replaces && task === "requirements" ? "기존 요구사항과 견적 초안 항목을 이 결과로 교체할까요? 승인된 Scope는 변경되지 않습니다." : replaces && task === "questions" ? "답변 없는 기존 질문을 이 결과로 교체할까요? 답변된 질문은 보존됩니다." : undefined}><input type="hidden" name="result" value={JSON.stringify(result)} />
    {"projectType" in result && <><label>프로젝트 유형<input required value={result.projectType} onChange={e => setResult({ ...result, projectType: e.target.value })} /></label><label>요청 요약<textarea required value={result.summary} onChange={e => setResult({ ...result, summary: e.target.value })} /></label>{result.features.map((item, i) => <details key={i}><summary>{item.title}</summary><div className="detail-body"><Feature value={item} onChange={value => setResult({ ...result, features: result.features.map((r, index) => index === i ? { ...value, confidence: r.confidence } : r) })} /></div></details>)}<h3>확인이 필요한 내용</h3>{result.missingInformation.map((q, i) => <label key={i}>질문 {i + 1}<textarea value={q.question} onChange={e => setResult({ ...result, missingInformation: result.missingInformation.map((r, index) => index === i ? { ...r, question: e.target.value } : r) })} /></label>)}</>}
    {"questions" in result && result.questions.map((q, i) => <div className="stack" key={i}><label>질문 {i + 1}<textarea required value={q.question} onChange={e => setResult({ ...result, questions: result.questions.map((r, index) => index === i ? { ...r, question: e.target.value } : r) })} /></label><label>질문 이유<input value={q.reason} onChange={e => setResult({ ...result, questions: result.questions.map((r, index) => index === i ? { ...r, reason: e.target.value } : r) })} /></label><button className="button secondary" type="button" disabled={result.questions.length === 1} onClick={() => setResult({ ...result, questions: result.questions.filter((_, index) => index !== i) })}>질문 제외</button></div>)}
    {"requirements" in result && result.requirements.map((item, i) => <details key={i}><summary>{i + 1}. {item.title}</summary><div className="detail-body"><Feature value={item} onChange={value => setResult({ ...result, requirements: result.requirements.map((r, index) => index === i ? value : r) })} /><button className="button secondary mt-4" type="button" disabled={result.requirements.length === 1} onClick={() => setResult({ ...result, requirements: result.requirements.filter((_, index) => index !== i) })}>범위에서 제외</button></div></details>)}
    {"items" in result && result.items.map((item, i) => <div className="stack" key={item.requirementId}><h3>{requirements.find(r => r.id === item.requirementId)?.title ?? "요구사항"}</h3><div className="hours-grid">{roles.map(role => <label key={role}>{roleLabels[role]} (시간)<input type="number" min={0} max={2000} step={0.5} required value={item.hours[role]} onChange={e => setResult({ ...result, items: result.items.map((r, index) => index === i ? { ...r, hours: { ...r.hours, [role]: Number(e.target.value) } } : r) })} /></label>)}</div><label>산정 근거<textarea required value={item.reason} onChange={e => setResult({ ...result, items: result.items.map((r, index) => index === i ? { ...r, reason: e.target.value } : r) })} /></label></div>)}
  </MutationForm></div></section>;
}
