"use client";
import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { Field, Textarea } from "./ui";
import { labels, roles, roleLabels, type Comparison, type RequirementInput } from "@/lib/model";
export function ChangeReviewFields({ request, review, existing, excluded, amount, adjustmentReason }: { request: string; review: Comparison; existing: {id:string;title:string}[]; excluded: string[]; amount: number | null; adjustmentReason: string }) {
  const [items, setItems] = useState<RequirementInput[]>(review.newRequirements);
  const [affected, setAffected] = useState(review.affectedExistingRequirements);
  const [removed, setRemoved] = useState(review.removedExclusions ?? []);
  function update(index:number,field:keyof RequirementInput,value:string) { setItems(rows=>rows.map((r,i)=>i===index ? {...r,[field]:value} : r)); }
  return <><Textarea label="고객 요청" name="request" value={request} required /><div className="form-grid"><label>범위 판정<select name="classification" defaultValue={review.classification}>{["UNCERTAIN","IN_SCOPE","PARTIALLY_IN_SCOPE","OUT_OF_SCOPE"].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label><Field label="판정 신뢰도 (0~1)" name="confidence" type="number" value={review.confidence} min={0} max={1} step={0.01} required /></div><Textarea label="판정 근거" name="reason" value={review.reason} required /><label>영향을 받는 기존 요구사항</label><div className="stack" style={{gap:8}}>{existing.map(r=><label key={r.id} className="check-label"><input type="checkbox" checked={affected.includes(r.id)} onChange={e=>setAffected(ids=>e.target.checked ? [...ids,r.id] : ids.filter(id=>id!==r.id))} />{r.title}</label>)}</div><input type="hidden" name="affectedExistingRequirements" value={affected.join(",")} />
  <div className="row"><h3>추가되는 요구사항</h3><button type="button" className="button secondary small" onClick={()=>setItems(rows=>[...rows,{title:"",category:"기능",description:"",type:"FEATURE",priority:"MEDIUM"}])} disabled={items.length>=30}><Plus size={13} />기능 추가</button></div><input type="hidden" name="newRequirements" value={JSON.stringify(items)} />
  {excluded.length > 0 && <fieldset><legend>새 기능으로 해제되는 기존 제외 항목</legend><p className="text-xs mb-3">해당 항목 전체가 추가 요구사항에 포함될 때만 선택하세요. 고객 승인 후 새 버전에서만 해제됩니다.</p>{excluded.map(item=><label key={item} className="check-label"><input type="checkbox" checked={removed.includes(item)} onChange={e=>setRemoved(rows=>e.target.checked ? [...rows,item] : rows.filter(r=>r!==item))} />{item}</label>)}</fieldset>}<input type="hidden" name="removedExclusions" value={JSON.stringify(removed)} />
  {items.map((r,i)=><div key={i} className="card card-body"><div className="row mb-4"><small>추가 기능 {i+1}</small><button type="button" className="text-button" aria-label={`추가 기능 ${i+1} 삭제`} onClick={()=>setItems(rows=>rows.filter((_,index)=>index!==i))}><Trash2 size={14} /></button></div><div className="form-grid"><label>기능 이름<input value={r.title} onChange={e=>update(i,"title",e.target.value)} required maxLength={160} /></label><label>분류<input value={r.category} onChange={e=>update(i,"category",e.target.value)} required maxLength={160} /></label><label>유형<select value={r.type} onChange={e=>update(i,"type",e.target.value)}>{["FEATURE","NON_FUNCTIONAL","DESIGN","INFRA","EXTERNAL_INTEGRATION"].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label><label>우선순위<select value={r.priority} onChange={e=>update(i,"priority",e.target.value)}>{["HIGH","MEDIUM","LOW"].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label><label className="wide">기능 설명<textarea value={r.description} onChange={e=>update(i,"description",e.target.value)} required maxLength={5000} rows={3} /></label></div></div>)}
  <div className="hours-grid">{roles.map(role=><Field key={role} name={`estimatedWork.${role}`} label={`${roleLabels[role]} 추가 시간`} type="number" value={review.estimatedWork[role]} min={0} max={2000} step={0.5} required />)}</div><div className="form-grid"><Field label="일정 영향 (추가 일수)" name="scheduleImpactDays" type="number" value={review.scheduleImpactDays} min={0} max={365} required /><Field label="추가 금액 조정 (선택 · KRW)" name="overrideAmount" type="number" value={amount} min={0} max={1e12} /></div><Textarea label="금액 조정 이유 (자동 산정이면 비워두세요)" name="adjustmentReason" value={adjustmentReason} rows={2} /><p className="text-xs">기존 범위에 포함되는 요청은 추가 기능과 추가 시간·비용·일수를 모두 비워야 합니다. 불확실한 판정은 고객에게 보낼 수 없습니다.</p></>;
}
