import Link from "next/link";
import { ArrowUpRight, Layers3, Plus, Sparkles } from "lucide-react";
import type { ReactNode } from "react";
import { labels } from "@/lib/model";
export function Logo() { return <Link href="/dashboard" className="logo"><span className="logo-mark"><Layers3 size={22} strokeWidth={2.2} /></span>scopeflow<span className="logo-dot">.</span></Link>; }
export function Badge({ value }: { value: string }) { return <span className={`badge ${["APPROVED", "ACTIVE", "IN_SCOPE", "SUCCESS", "COMPLETED"].includes(value) ? "green" : ["REJECTED", "OUT_OF_SCOPE", "FAILED", "CANCELLED"].includes(value) ? "red" : ["DRAFT", "SUPERSEDED"].includes(value) ? "gray" : "amber"}`}><span />{labels[value] || value}</span>; }
export function PageHeading({ eyebrow, title, description, children }: { eyebrow?: string; title: string; description?: string; children?: ReactNode }) { return <header className="page-heading"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description && <p>{description}</p>}</div><div className="heading-actions">{children}</div></header>; }
export function Card({ title, hint, children, className = "", action }: { title?: string; hint?: string; children: ReactNode; className?: string; action?: ReactNode }) { return <section className={`card ${className}`}>{title && <div className="card-heading"><div><h2>{title}</h2>{hint && <p>{hint}</p>}</div>{action}</div>}{children}</section>; }
export function Empty({ title, description, href, cta }: { title: string; description: string; href?: string; cta?: string }) { return <div className="empty"><div className="empty-icon"><Layers3 size={25} /></div><h3>{title}</h3><p>{description}</p>{href && <Link href={href} className="button secondary"><Plus size={15} />{cta || "시작하기"}</Link>}</div>; }
export function AiNotice({ configured }: { configured: boolean }) { return <div className="notice"><Sparkles size={17} /><span>{configured ? "AI 결과가 프로젝트에 반영됩니다. 실행 후 내용을 검토해주세요." : "AI 연결 전에도 직접 입력으로 진행할 수 있습니다. AI 설정에서 연결 상태를 확인해주세요."}</span><Link href="/settings/ai">AI 설정 <ArrowUpRight size={13} /></Link></div>; }
export function Field({ label, name, value, type = "text", required = false, placeholder, min, max, step }: { label: string; name: string; value?: string | number | null; type?: string; required?: boolean; placeholder?: string; min?: number; max?: number; step?: number }) { return <label>{label}<input name={name} type={type} defaultValue={value ?? ""} required={required} placeholder={placeholder} min={min} max={max} step={step} maxLength={type === "text" ? 5000 : undefined} /></label>; }
export function Textarea({ label, name, value, required = false, placeholder, rows = 4 }: { label: string; name: string; value?: string; required?: boolean; placeholder?: string; rows?: number }) { return <label>{label}<textarea name={name} defaultValue={value} required={required} placeholder={placeholder} rows={rows} maxLength={5000} /></label>; }
