import Link from "next/link";
import { projectData } from "@/lib/queries";
import { Card, Field, Textarea } from "@/components/ui";
import { MutationForm } from "@/components/form";
import { dateLabel, won } from "@/lib/model";
export default async function Overview({ params }: { params: Promise<{ projectId: string }> }) {
  const {projectId} = await params; const d = await projectData(projectId); const locked = d.scopes.some(s => ["APPROVED", "WAITING_APPROVAL"].includes(s.status));
  return <div className="two-col"><div className="stack"><Card title="고객의 첫 요청" hint="원문의 의도부터 이해하는 것이 좋은 시작입니다."><div className="card-body"><p className="prose">{d.initial?.content}</p>{!locked && <details><summary>원문 수정</summary><MutationForm action="initial.save" payload={{projectId}}><Textarea name="content" label="고객 원문" value={d.initial?.content} required /></MutationForm></details>}<div className="actions-row"><Link className="button secondary" href={`/projects/${projectId}/requirements`}>요구사항 정리하기 →</Link></div></div></Card><Card title="고객 피드백"><div className="card-body">{d.feedback.length ? d.feedback.map(f => <div key={f.id} className="activity-item"><div><strong>{f.name}</strong><p className="prose">{f.message}</p><small>{dateLabel(f.createdAt)}</small></div></div>) : <p className="text-xs">고객의 답변과 수정 요청이 여기에 기록됩니다.</p>}</div></Card></div><div className="stack"><Card title="프로젝트 정보"><div className="card-body"><dl className="info-grid"><div><dt>고객</dt><dd>{d.client.company || d.client.name}</dd></div><div><dt>담당자</dt><dd>{d.client.name}</dd></div><div><dt>예산</dt><dd>{d.project.budget == null ? "미정" : won(d.project.budget)}</dd></div><div><dt>희망 완료일</dt><dd>{dateLabel(d.project.deadline)}</dd></div><div><dt>요구사항</dt><dd>{d.requirements.length}개</dd></div><div><dt>Scope 버전</dt><dd>{d.scopes.length}개</dd></div></dl>{d.project.referenceUrl && <p className="mt-5"><a className="inline-link" href={d.project.referenceUrl} target="_blank" rel="noreferrer">참고 사이트 ↗</a></p>}{d.project.notes && <p className="prose mt-5">{d.project.notes}</p>}</div></Card>
  <Card title="프로젝트 관리"><div className="card-body">{!locked && <details><summary>기본 정보 수정</summary><MutationForm action="project.update" payload={{projectId, clientId:d.client.id}}><Field label="프로젝트 이름" name="name" value={d.project.name} required /><Field label="예산" name="budget" type="number" min={0} value={d.project.budget} /><Field label="희망 완료일" name="deadline" type="date" value={d.project.deadline} /><Field label="참고 URL" name="referenceUrl" value={d.project.referenceUrl} /><Textarea label="메모" name="notes" value={d.project.notes} /></MutationForm></details>}<MutationForm action="project.status" payload={{projectId}} submit="상태 변경"><label>진행 상태<select name="status" defaultValue="COMPLETED"><option value="COMPLETED">완료</option><option value="CANCELLED">취소</option><option value="ACTIVE">진행 중</option></select></label></MutationForm>{!d.scopes.length && <div className="actions-row"><MutationForm className="compact" action="project.delete" payload={{projectId}} submit="프로젝트 삭제" confirm="문서·공유·AI 사용 이력이 없는 이 프로젝트를 삭제할까요?" /></div>}</div></Card></div></div>;
}
