import assert from "node:assert/strict";
import test from "node:test";

test("review → scope approval → change approval, immutable history and workspace isolation", { skip: !process.env.TEST_DATABASE_URL, timeout: 120_000 }, async () => {
  process.env.DATABASE_URL = process.env.TEST_DATABASE_URL;
  process.env.BETTER_AUTH_SECRET ??= `test-only-${"x".repeat(32)}`;
  process.env.BETTER_AUTH_URL ??= "http://localhost:3001";
  process.env.FRONTEND_URL ??= "http://localhost:3000";
  process.env.GROQ_API_KEY = "test-only";
  const [{ prisma }, { scopeService, clientAccessService, changeRequestService }, { projectService, requirementService }, { aiWorkflowService }, { executeCommand, commandSchema }] = await Promise.all([
    import("@/lib/db/prisma"), import("@/lib/services/workflow.service"), import("@/lib/services/core.service"), import("@/lib/services/ai-workflow.service"), import("@/lib/services/command.service"),
  ]);
  const originalFetch = globalThis.fetch;
  const suffix = crypto.randomUUID();
  const user = await prisma.user.create({ data: { id: suffix, name: "Integration Owner", email: `${suffix}@example.invalid` } });
  const rates = { frontend: 50000, backend: 60000, design: 45000, qa: 40000 };
  const workspace = await prisma.workspace.create({ data: { name: `Integration ${suffix}`, members: { create: { userId: user.id, role: "OWNER" } }, rateCard: { create: { rates } } } });
  const foreign = await prisma.workspace.create({ data: { name: "Other workspace" } });
  const ctx = { userId: user.id, workspaceId: workspace.id, role: "OWNER" as const };
  const feature = { category: "인증", title: "로그인", description: "이메일로 로그인한다.", type: "FEATURE" as const, priority: "HIGH" as const };
  const hours = { frontend: 2, backend: 2, design: 0, qa: 1 };
  try {
    const create = commandSchema.parse({ action: "project.create", name: "UX integration", newClient: { name: "Client", email: "client@example.invalid" }, content: "이메일 로그인이 필요합니다.", budget: "", deadline: "2026-12-01" });
    assert.equal(create.action, "project.create");
    if (create.action !== "project.create") throw new Error("schema");
    const result = await executeCommand(ctx, create);
    const id = result.redirect!.split("/")[2];
    assert.equal((await projectService.get(ctx, id))?.client.name, "Client");
    await assert.rejects(projectService.get({ ...ctx, workspaceId: foreign.id }, id), /찾을 수/);
    await assert.rejects(aiWorkflowService.estimate({ ...ctx, role: "MEMBER" }, id), /소유자/);
    const manual = await requirementService.create(ctx, id, { ...feature, source: "OWNER_MANUAL" });

    globalThis.fetch = async () => { throw new Error("simulated provider outage"); };
    await assert.rejects(aiWorkflowService.analyzeRequest(ctx, id, "실패해도 보존되는 원문"), /AI/);
    assert.equal((await prisma.initialRequest.findUnique({ where: { projectId: id } }))?.content, "실패해도 보존되는 원문");
    const analysis = { projectType: "웹앱", summary: "인증 기능", features: [{ ...feature, confidence: 0.8 }], budget: { amount: null, currency: "KRW" }, desiredDeadline: null, missingInformation: [{ question: "로그인 방식은?", reason: "범위 확인" }] };
    const mock = (data: unknown) => { globalThis.fetch = async () => Response.json({ choices: [{ message: { content: JSON.stringify(data) } }], usage: { prompt_tokens: 4, completion_tokens: 2 } }); };
    mock(analysis);
    let draft = await aiWorkflowService.analyzeRequest(ctx, id, "실패해도 보존되는 원문");
    assert.equal((await prisma.initialRequest.findUnique({ where: { projectId: id } }))?.analysis, null);
    assert.ok((await prisma.project.findUniqueOrThrow({ where: { id } })).aiDrafts);
    await aiWorkflowService.apply(ctx, id, "initial", draft.revision, analysis);
    mock({ questions: [{ question: "로그인 방식은?", reason: "범위 확인" }] });
    draft = await aiWorkflowService.generateQuestions(ctx, id);
    assert.equal(await prisma.clarificationQuestion.count({ where: { projectId: id } }), 0);
    await aiWorkflowService.apply(ctx, id, "questions", draft.revision, draft.result);
    const question = await prisma.clarificationQuestion.findFirstOrThrow({ where: { projectId: id } });
    const questionLink = await clientAccessService.create(ctx, id, "QUESTIONS");
    await clientAccessService.answer(questionLink.token, question.id, "이메일만 지원", "Client");
    mock({ requirements: [feature] });
    draft = await aiWorkflowService.generateRequirements(ctx, id);
    assert.equal((await prisma.requirement.findUniqueOrThrow({ where: { id: manual.id } })).title, feature.title, "AI generation never overwrites manual requirements");
    await aiWorkflowService.apply(ctx, id, "requirements", draft.revision, draft.result);
    const requirement = await prisma.requirement.findFirstOrThrow({ where: { projectId: id } });
    mock({ items: [{ requirementId: requirement.id, hours, complexity: "LOW", reason: "구현과 검증" }] });
    draft = await aiWorkflowService.estimate(ctx, id);
    assert.equal(await prisma.estimate.count({ where: { projectId: id } }), 0);
    await aiWorkflowService.apply(ctx, id, "estimate", draft.revision, draft.result);
    await assert.rejects(aiWorkflowService.apply(ctx, id, "estimate", draft.revision, draft.result), /이전 결과/);
    let scope = await scopeService.create(ctx, id, { document: { durationDays: 25 } });
    await requirementService.update(ctx, id, requirement.id, { description: "이메일 인증을 포함한다." });
    await assert.rejects(scopeService.requestApproval(ctx, id, scope.id), /변경/);
    scope = await scopeService.update(ctx, id, scope.id, {});
    await assert.rejects(scopeService.requestApproval(ctx, id, scope.id), /작업량/);
    await aiWorkflowService.updateEstimate(ctx, id, { items: [{ requirementId: requirement.id, hours, complexity: "LOW", reason: "검토 완료" }], overrideTotal: 300000, adjustmentReason: "합의 가격" });
    scope = await scopeService.update(ctx, id, scope.id, {});
    const link = await clientAccessService.create(ctx, id, "SCOPE", scope.id);
    assert.equal(((await clientAccessService.get(link.token)).scope?.document as { durationDays: number }).durationDays, 25);
    await assert.rejects(requirementService.update(ctx, id, requirement.id, { title: "변조" }), /승인/);
    await assert.rejects(aiWorkflowService.updateEstimate(ctx, id, { overrideTotal: 0, adjustmentReason: "변조" }), /승인/);
    const decisions = await Promise.allSettled([clientAccessService.decide(link.token, "APPROVE", "Client", ""), clientAccessService.decide(link.token, "APPROVE", "Client", "")]);
    assert.equal(decisions.filter(d => d.status === "fulfilled").length, 1, "duplicate decisions cannot both commit");
    assert.equal((await clientAccessService.get(link.token)).receipt?.decision, "APPROVE", "refresh retains receipt");
    const original = await prisma.scope.findUniqueOrThrow({ where: { id: scope.id } });
    await assert.rejects(scopeService.update(ctx, id, scope.id, {}), /승인/);
    await assert.rejects(clientAccessService.answer(questionLink.token, question.id, "사후 답변", "Client"), /승인/);

    const change = await changeRequestService.create(ctx, id, "리뷰를 추가해주세요");
    const review = { classification: "OUT_OF_SCOPE", confidence: 0.7, reason: "기존 로그인에 없는 기능", newRequirements: [{ ...feature, category: "리뷰", title: "리뷰 작성" }], affectedExistingRequirements: [], removedExclusions: [], estimatedWork: hours, scheduleImpactDays: 2 };
    mock(review);
    await aiWorkflowService.compareChange(ctx, id, change.id);
    await assert.rejects(changeRequestService.requestApproval(ctx, id, change.id), /내부 검토/);
    await changeRequestService.review(ctx, id, change.id, { review, overrideAmount: 250000, adjustmentReason: "고객 협의" });
    const changeLink = await changeRequestService.requestApproval(ctx, id, change.id);
    await clientAccessService.decide(changeLink.token, "APPROVE", "Client", "");
    const changed = await prisma.changeRequest.findUniqueOrThrow({ where: { id: change.id } });
    const version = await prisma.scope.findUniqueOrThrow({ where: { id: changed.resultScopeId! } });
    assert.equal(version.majorVersion, 1); assert.equal(version.minorVersion, 1);
    assert.equal((version.document as { estimate: { total: number } }).estimate.total, 550000);
    assert.deepEqual((await prisma.scope.findUniqueOrThrow({ where: { id: scope.id } })).document, original.document);
    assert.equal((await clientAccessService.get(changeLink.token)).change?.resultScope?.minorVersion, 1);
    await assert.rejects(changeRequestService.withdraw(ctx, id, change.id, true), /이미 처리/);
    assert.equal((await projectService.get(ctx, id))?.status, "ACTIVE");
    await executeCommand(ctx, { action: "share.revoke", projectId: id, tokenId: (await prisma.clientAccessToken.findFirstOrThrow({ where: { changeRequestId: change.id } })).id });
    await assert.rejects(clientAccessService.get(changeLink.token), /공유 링크/);
  } finally { globalThis.fetch = originalFetch; await prisma.$disconnect(); }
});
