import { ProjectState } from "@/components/next-step";
import Link from "next/link";
import { projectData } from "@/lib/queries";
import { AiNotice, Card, Empty, Textarea, Badge } from "@/components/ui";
import { AIButton } from "@/components/ai";
import { AIReview } from "@/components/ai-review";
import { MutationForm } from "@/components/form";
import { RequirementFields } from "@/components/requirements";
import { labels, requirementSchema } from "@/lib/model";
export default async function Requirements({ params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = await params; const d = await projectData(projectId);
  const locked = ["COMPLETED", "CANCELLED"].includes(d.project.status) || d.scopes.some(s => ["APPROVED", "WAITING_APPROVAL"].includes(s.status));
  const owner = d.ctx.role === "OWNER";
  const drafts = d.project.aiDrafts ?? {};
  const reviewing = Object.entries(drafts).some(([task, draft]) => task !== "estimate" && draft.revision === d.project.revision);
  const unanswered = d.questions.filter(q => !q.answer).length;
  const ready = d.requirements.some(r => r.status === "CONFIRMED") && !d.requirements.some(r => r.status === "PENDING") && !unanswered;
  const task = !d.initial?.analysis ? "initial" : !d.questions.length && d.initial.analysis.missingInformation.length ? "questions" : "requirements";
  return <div className="stack"><ProjectState project={d.project} /><AiNotice configured />
    {locked ? <div className="notice"><span>합의 중이거나 승인된 요구사항은 보호됩니다. 추가 범위는 변경 요청으로 관리하세요.</span><Link href={`/projects/${projectId}/scope`}>현재 Scope 보기 →</Link></div> : !reviewing && <section className="next-step"><div><small>현재 단계 · 요구사항</small><h2>{ready ? "요구사항이 준비되었습니다" : d.questions.length > 0 && !unanswered ? "고객 답변이 도착했습니다" : unanswered ? "고객 답변을 기다리고 있습니다" : "고객 요청에서 범위를 정리하세요"}</h2><p>{ready ? "확정 항목의 작업량과 견적을 검토하세요." : unanswered ? `${unanswered}개 질문에 답변이 필요합니다.` : "AI 결과는 수정·확인 후 반영합니다. 직접 입력도 가능합니다."}</p></div>{ready ? <Link className="button" href={`/projects/${projectId}/estimate`}>견적 만들기 →</Link> : unanswered ? owner && <MutationForm action="share.create" variant="primary" payload={{ projectId, purpose: "QUESTIONS" }} submit="고객에게 질문 전달" /> : owner && <AIButton projectId={projectId} task={task} primary />}</section>}
    {!locked && owner && (["initial", "questions", "requirements"] as const).map(task => drafts[task] && <AIReview key={task + drafts[task].createdAt} projectId={projectId} task={task} draft={drafts[task]} revision={d.project.revision} replaces={task === "requirements" ? d.requirements.length > 0 : task === "questions" && unanswered > 0} />)}
    <Card title="고객 요청 및 분석"><div className="card-body">
      <details open={!d.initial?.analysis}><summary>고객 원문 요청</summary>{!locked && owner ? <MutationForm action="initial.save" payload={{ projectId }} submit="원문 저장"><Textarea label="고객이 전달한 원문" name="content" value={d.initial?.content} required rows={5} /></MutationForm> : <p className="prose">{d.initial?.content}</p>}</details>
      {d.initial?.analysis && <><h3>{d.initial.analysis.projectType}</h3><p className="prose">{d.initial.analysis.summary}</p><div className="detail-meta mt-4">{d.initial.analysis.features.map((f, i) => <span key={i}>✓ {f.title}</span>)}</div>{d.initial.analysis.missingInformation.length > 0 && <details><summary>확인이 필요한 내용</summary><ul>{d.initial.analysis.missingInformation.map((q, i) => <li key={i}>{q.question}</li>)}</ul></details>}</>}
      {!locked && owner && <details><summary>AI 분석 도구 · 다시 정리하기</summary><div className="actions-row"><AIButton projectId={projectId} task="initial" /><AIButton projectId={projectId} task="questions" /><AIButton projectId={projectId} task="requirements" /></div></details>}
    </div></Card>
    <div className="two-col"><div className="stack"><Card title={`요구사항 · 확정 ${d.requirements.filter(r => r.status === "CONFIRMED").length} / 확인 필요 ${d.requirements.filter(r => r.status === "PENDING").length}`} hint="견적과 Scope에는 확정된 항목만 포함됩니다.">
      {d.requirements.length ? [...new Set(d.requirements.map(r => r.category))].map(category => <section key={category}><h3 className="category-heading">{category}</h3><div className="detail-list">{d.requirements.filter(r => r.category === category).map(r => <details key={r.id}><summary><span>{r.title}</span><span className="detail-meta"><span>{r.status === "PENDING" ? "확인 필요" : labels[r.status]}</span>{r.source === "CHANGE_REQUEST" && <Badge value={r.source} />}</span></summary><div className="detail-body"><div className="detail-meta"><span>{labels[r.type]}</span><span>{labels[r.priority]}</span><span>{labels[r.source]}</span></div>{locked ? <p className="prose">{r.description}</p> : <><MutationForm action="requirement.save" payload={{ projectId, requirementId: r.id }}><RequirementFields value={{ ...requirementSchema.parse(r), status: r.status }} /></MutationForm><div className="actions-row"><MutationForm className="compact" variant="danger" action="requirement.delete" payload={{ projectId, requirementId: r.id }} submit="요구사항 삭제" confirm="이 요구사항과 연결된 견적 초안 항목을 삭제할까요?" /></div></>}</div></details>)}</div></section>) : <Empty title="아직 확정된 요구사항이 없습니다" description="고객 답변을 바탕으로 AI 초안을 검토하거나 직접 추가하세요." />}
    </Card>{!locked && <Card title="요구사항 직접 추가"><details><summary>직접 입력하기</summary><div className="card-body"><MutationForm action="requirement.save" payload={{ projectId }} submit="요구사항 추가"><RequirementFields /></MutationForm></div></details></Card>}</div>
    <div id="questions"><Card title={`고객에게 확인할 질문 ${d.questions.length}/8`} hint={unanswered ? `답변 대기 ${unanswered}개` : d.questions.length ? "답변이 도착했습니다. 요구사항을 업데이트해주세요." : "꼭 필요한 질문만 검토해 전달하세요."}><div className="card-body">
      {d.questions.map(({ question: q, answer }, i) => <details key={q.id} open={!answer}><summary>{i + 1}. {q.question}</summary><div className="detail-body"><p className="text-xs mb-4">{q.reason}</p>{!locked ? <><MutationForm action="answer.save" payload={{ projectId, questionId: q.id }} submit="답변 저장"><Textarea label="고객 답변" name="content" value={answer?.content} required rows={3} /></MutationForm><details><summary>질문 편집</summary><MutationForm action="question.save" payload={{ projectId, questionId: q.id }} confirm={answer ? "질문을 바꾸면 기존 답변은 삭제됩니다. 계속할까요?" : undefined}><Textarea label="질문" name="question" value={q.question} required rows={2} /><Textarea label="질문 이유" name="reason" value={q.reason} rows={2} /></MutationForm><MutationForm className="compact" variant="danger" action="question.delete" payload={{ projectId, questionId: q.id }} submit="질문 삭제" confirm="질문과 답변을 삭제할까요?" /></details></> : <p className="prose">{answer?.content || "답변 없음"}</p>}</div></details>)}
      {!locked && <><details><summary>질문 직접 추가</summary><MutationForm action="question.save" payload={{ projectId }} submit="질문 추가" disabled={d.questions.length >= 8}><Textarea label="질문" name="question" required rows={2} /><Textarea label="질문 이유" name="reason" rows={2} /></MutationForm></details>{owner && d.questions.length > 0 && !unanswered && <AIButton projectId={projectId} task="requirements" />}</>}
    </div></Card></div></div>
  </div>;
}
