import { projectData } from "@/lib/queries";
import { AiNotice, Card, Empty, Textarea } from "@/components/ui";
import { AIButton } from "@/components/ai";
import { MutationForm } from "@/components/form";
import { RequirementFields } from "@/components/requirements";
import { labels, requirementSchema } from "@/lib/model";
export default async function Requirements({params}: {params:Promise<{projectId:string}>}) {
  const {projectId} = await params; const d = await projectData(projectId);
  const locked = d.scopes.some(s=>["APPROVED","WAITING_APPROVAL"].includes(s.status));
  return <><AiNotice configured />{!locked && <div className="actions-row mb-6"><AIButton projectId={projectId} task="initial" /><AIButton projectId={projectId} task="questions" /><AIButton projectId={projectId} task="requirements" /></div>}<div className="stack"><div className="two-col"><div className="stack"><Card title={`확정 요구사항 ${d.requirements.length}`} hint={locked ? "합의한 요구사항입니다. 추가·수정은 변경 요청으로 관리하세요." : "기능과 완료 기준을 명확하게 정리하세요."}><div className="detail-list">{d.requirements.length ? d.requirements.map((r,i)=><details key={r.id}><summary><span className="requirement-title"><span className="requirement-number">REQ-{String(i+1).padStart(2,"0")}</span>{r.title}</span></summary><div className="detail-body"><div className="detail-meta"><span>{r.category}</span><span>{labels[r.type]}</span><span>{labels[r.priority]}</span><span>{labels[r.source]}</span></div>{locked ? <p className="prose">{r.description}</p> : <><MutationForm action="requirement.save" payload={{projectId,requirementId:r.id}}><RequirementFields value={requirementSchema.parse(r)} /></MutationForm><div className="actions-row"><MutationForm className="compact" action="requirement.delete" payload={{projectId,requirementId:r.id}} submit="요구사항 삭제" confirm="이 요구사항과 연결된 견적 초안 항목을 삭제할까요?" /></div></>}</div></details>) : <Empty title="요구사항을 함께 정리해요" description="AI로 생성하거나 아래에서 직접 추가할 수 있어요." />}</div></Card>{!locked && <Card title="요구사항 직접 추가"><div className="card-body"><MutationForm action="requirement.save" payload={{projectId}} submit="요구사항 추가"><RequirementFields /></MutationForm></div></Card>}</div>
  <div className="stack"><Card title={`고객에게 확인할 질문 ${d.questions.length}/8`} hint="범위를 확정하기 위해 꼭 필요한 질문만 남겨보세요."><div className="card-body">{d.questions.length ? d.questions.map(({question:q,answer},i)=><details key={q.id} open={!answer}><summary><span>{i+1}. {q.question}</span></summary><div className="detail-body"><p className="text-xs mb-4">{q.reason}</p>{!locked ? <><MutationForm action="answer.save" payload={{projectId,questionId:q.id}} submit="답변 저장"><Textarea label="고객 답변" name="content" value={answer?.content} required rows={3} /></MutationForm><details><summary>질문 편집</summary><MutationForm action="question.save" payload={{projectId,questionId:q.id}}><Textarea label="질문" name="question" value={q.question} required rows={2} /><Textarea label="질문 이유" name="reason" value={q.reason} rows={2} /></MutationForm><div className="actions-row"><MutationForm className="compact" action="question.delete" payload={{projectId,questionId:q.id}} submit="질문 삭제" confirm="이 질문과 답변을 삭제할까요?" /></div></details></> : <p className="prose">{answer?.content || "답변 없음"}</p>}</div></details>) : <p className="text-xs">분석으로 질문을 생성하거나 직접 추가해주세요.</p>}{!locked && <><div className="actions-row"><MutationForm className="compact" action="share.create" payload={{projectId,purpose:"QUESTIONS"}} submit="고객 답변 링크 발급" /></div><details><summary>질문 직접 추가</summary><MutationForm action="question.save" payload={{projectId}} submit="질문 추가"><Textarea label="질문" name="question" required rows={2} /><Textarea label="질문 이유" name="reason" rows={2} /></MutationForm></details></>}</div></Card></div></div></div></>;
}
