import { and, eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { aiDrafts, rateCards } from "@/lib/db/schema";
import { projectData } from "@/lib/queries";
import { Card, Empty, Field, Textarea, AiNotice } from "@/components/ui";
import { AIButton, DraftPanel } from "@/components/ai";
import { MutationForm } from "@/components/form";
import { aiConfigured } from "@/lib/ai/provider";
import { calculateAmount, defaultRates, roles, roleLabels, won, zeroHours } from "@/lib/model";
export default async function Estimate({params}: {params:Promise<{projectId:string}>}) {
  const {projectId} = await params; const d = await projectData(projectId); const [draft] = await db.select().from(aiDrafts).where(and(eq(aiDrafts.projectId,projectId),eq(aiDrafts.action,"estimate"))); const [card] = await db.select().from(rateCards).where(eq(rateCards.workspaceId,d.ctx.workspaceId));
  const locked = d.scopes.some(s=>["APPROVED","WAITING_APPROVAL"].includes(s.status)); const rates = d.estimate?.rates || card?.rates || defaultRates;
  const sum = d.items.reduce((total,i)=>total+calculateAmount(i.hours,rates),0);
  const approved=d.scopes.find(s=>s.status==="APPROVED");
  if (approved) return <Card title={`승인된 견적 · v1.${approved.version-1}`} hint="추가 변경 승인 시 새 버전의 견적에 누적 반영됩니다."><div className="table-wrap"><table><thead><tr><th>기능 / 변경 요청</th><th>작업 시간</th><th>금액</th></tr></thead><tbody>{approved.document.estimate.items.map((item,i)=><tr key={i}><td>{item.title}<small>{item.reason}</small></td><td>{Object.values(item.hours).reduce((sum,h)=>sum+h,0)}h</td><td>{won(item.amount)}</td></tr>)}</tbody></table></div><div className="estimate-total"><div><p>누적 승인 견적</p><p>{approved.document.estimate.adjustmentReason}</p></div><strong>{won(approved.document.estimate.total)}</strong></div></Card>;
  return <><AiNotice configured={aiConfigured()} /><div className="stack">{!locked && <><AIButton projectId={projectId} task="estimate" /><DraftPanel draft={draft} /></>}<div className="two-col"><Card title="기능별 예상 작업량" hint="각 항목의 시간을 검토·저장해야 Scope 승인을 요청할 수 있습니다."><div className="detail-list">{d.requirements.length ? d.requirements.map(r=>{const item=d.items.find(i=>i.requirementId===r.id);return <details key={r.id} open={!item?.reviewed}><summary><div><strong>{r.title}</strong><p className="text-xs">{item?.reviewed ? "검토 완료" : "시간 검토 필요"} · {won(calculateAmount(item?.hours || zeroHours,rates))}</p></div></summary><div className="detail-body"><MutationForm action="estimate.item" payload={{projectId,requirementId:r.id}} submit="검토 완료 · 저장" disabled={locked}><div className="hours-grid">{roles.map(role=><Field key={role} label={`${roleLabels[role]} (시간)`} name={`hours.${role}`} type="number" min={0} max={2000} step={0.5} value={item?.hours[role] || 0} required />)}</div><Textarea label="산정 근거" name="reason" value={item?.reason || r.description} required rows={2} /></MutationForm></div></details>;}) : <Empty title="견적을 낼 요구사항이 없어요" description="요구사항을 먼저 확정해주세요." href={`/projects/${projectId}/requirements`} cta="요구사항 정리" />}</div></Card><div className="stack"><Card title="견적 요약"><div className="card-body"><dl className="info-grid">{roles.map(role=><div key={role}><dt>{roleLabels[role]} · 시간당</dt><dd>{won(rates[role])}</dd></div>)}</dl></div><div className="estimate-total"><div><p>최종 예상 견적 · KRW</p><strong>{won(d.estimate?.overrideTotal ?? sum)}</strong></div></div><div className="card-body"><p className="text-xs mb-5">기능별 합계 {won(sum)} · 세금 및 외부 서비스 비용은 Scope의 가정 사항에서 협의하세요.</p><MutationForm action="estimate.total" payload={{projectId}} disabled={locked}><Field label="최종 금액 조정 (비워두면 자동 합계)" name="overrideTotal" type="number" min={0} max={1e12} value={d.estimate?.overrideTotal} /><Textarea label="금액 조정 이유" name="adjustmentReason" value={d.estimate?.adjustmentReason} rows={3} /></MutationForm></div></Card></div></div></div></>;
}
