import { pgTable, text, timestamp, boolean, integer, jsonb, doublePrecision, uniqueIndex, index, foreignKey, check } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import type { Comparison, Hours, Rates, ScopeDocument } from "../model";
import { defaultRates, zeroHours } from "../model";

const pk = () => text("id").primaryKey().$defaultFn(() => crypto.randomUUID());
const created = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
const updated = () => timestamp("updated_at", { withTimezone: true }).notNull().defaultNow();

export const user = pgTable("users", { id: pk(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("email_verified").notNull().default(false), image: text("image"), createdAt: created(), updatedAt: updated() });
export const session = pgTable("sessions", { id: pk(), token: text("token").notNull().unique(), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), ipAddress: text("ip_address"), userAgent: text("user_agent"), createdAt: created(), updatedAt: updated() }, t => [index("session_user_idx").on(t.userId)]);
export const account = pgTable("accounts", { id: pk(), accountId: text("account_id").notNull(), providerId: text("provider_id").notNull(), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), accessToken: text("access_token"), refreshToken: text("refresh_token"), idToken: text("id_token"), accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }), refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }), scope: text("scope"), password: text("password"), createdAt: created(), updatedAt: updated() }, t => [index("account_user_idx").on(t.userId)]);
export const verification = pgTable("verifications", { id: pk(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), createdAt: created(), updatedAt: updated() });
export const rateLimit = pgTable("auth_rate_limits", { id: pk(), key: text("key").notNull().unique(), count: integer("count").notNull(), lastRequest: doublePrecision("last_request").notNull() });

export const workspaces = pgTable("workspaces", { id: pk(), name: text("name").notNull(), creditLimit: integer("credit_limit").notNull().default(500), userCreditLimit: integer("user_credit_limit").notNull().default(300), creditCosts: jsonb("credit_costs").$type<Record<string, number>>().notNull().default({ initial: 2, questions: 1, requirements: 2, estimate: 2, summary: 2, compare: 3 }), createdAt: created() });
export const members = pgTable("workspace_members", { id: pk(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), userId: text("user_id").notNull().references(() => user.id), role: text("role", { enum: ["OWNER", "MEMBER"] }).notNull().default("MEMBER"), createdAt: created() }, t => [uniqueIndex("member_workspace_user_unique").on(t.workspaceId, t.userId)]);
export const clients = pgTable("clients", { id: pk(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), name: text("name").notNull(), email: text("email").notNull(), company: text("company").notNull().default(""), phone: text("phone").notNull().default(""), notes: text("notes").notNull().default(""), createdAt: created(), updatedAt: updated() }, t => [uniqueIndex("client_workspace_id_unique").on(t.workspaceId, t.id)]);
export const projects = pgTable("projects", { id: pk(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), clientId: text("client_id").notNull(), name: text("name").notNull(), status: text("status", { enum: ["DRAFT", "REQUIREMENT_GATHERING", "WAITING_SCOPE_APPROVAL", "ACTIVE", "WAITING_CHANGE_APPROVAL", "COMPLETED", "CANCELLED"] }).notNull().default("DRAFT"), budget: doublePrecision("budget"), deadline: text("deadline"), referenceUrl: text("reference_url").notNull().default(""), notes: text("notes").notNull().default(""), revision: integer("revision").notNull().default(0), createdAt: created(), updatedAt: updated() }, t => [foreignKey({ columns: [t.workspaceId, t.clientId], foreignColumns: [clients.workspaceId, clients.id] }), index("project_workspace_idx").on(t.workspaceId)]);
export const initialRequests = pgTable("initial_requests", { id: pk(), projectId: text("project_id").notNull().unique().references(() => projects.id, { onDelete: "cascade" }), content: text("content").notNull(), analysis: jsonb("analysis").$type<Record<string, unknown>>(), createdAt: created(), updatedAt: updated() });
export const questions = pgTable("clarification_questions", { id: pk(), projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), question: text("question").notNull(), reason: text("reason").notNull().default(""), position: integer("position").notNull().default(0), createdAt: created() });
export const answers = pgTable("clarification_answers", { id: pk(), questionId: text("question_id").notNull().unique().references(() => questions.id, { onDelete: "cascade" }), content: text("content").notNull(), author: text("author").notNull(), updatedAt: updated() });
export const requirements = pgTable("requirements", { id: pk(), projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), category: text("category").notNull(), title: text("title").notNull(), description: text("description").notNull(), type: text("type").notNull().default("FEATURE"), priority: text("priority").notNull().default("MEDIUM"), status: text("status").notNull().default("CONFIRMED"), source: text("source").notNull(), createdAt: created(), updatedAt: updated() }, t => [index("requirement_project_idx").on(t.projectId)]);
export const rateCards = pgTable("rate_cards", { id: pk(), workspaceId: text("workspace_id").notNull().unique().references(() => workspaces.id), rates: jsonb("rates").$type<Rates>().notNull().default(defaultRates), updatedAt: updated() });
export const estimates = pgTable("estimates", { id: pk(), projectId: text("project_id").notNull().unique().references(() => projects.id, { onDelete: "cascade" }), rates: jsonb("rates").$type<Rates>().notNull().default(defaultRates), overrideTotal: doublePrecision("override_total"), adjustmentReason: text("adjustment_reason").notNull().default(""), updatedAt: updated() });
export const estimateItems = pgTable("estimate_items", { id: pk(), estimateId: text("estimate_id").notNull().references(() => estimates.id, { onDelete: "cascade" }), requirementId: text("requirement_id").notNull().references(() => requirements.id, { onDelete: "cascade" }), hours: jsonb("hours").$type<Hours>().notNull().default(zeroHours), complexity: text("complexity").notNull().default("MEDIUM"), reason: text("reason").notNull().default("수동 입력"), reviewed: boolean("reviewed").notNull().default(false) }, t => [uniqueIndex("estimate_requirement_unique").on(t.estimateId, t.requirementId)]);
export const scopes = pgTable("scopes", { id: pk(), projectId: text("project_id").notNull().references(() => projects.id), version: integer("version").notNull(), status: text("status", { enum: ["DRAFT", "WAITING_APPROVAL", "APPROVED", "SUPERSEDED"] }).notNull().default("DRAFT"), document: jsonb("document").$type<ScopeDocument>().notNull(), basedOnRevision: integer("based_on_revision").notNull(), approvedAt: timestamp("approved_at", { withTimezone: true }), approvedBy: text("approved_by"), createdAt: created() }, t => [uniqueIndex("scope_project_version_unique").on(t.projectId, t.version)]);
export const changes = pgTable("change_requests", { id: pk(), projectId: text("project_id").notNull().references(() => projects.id), number: integer("number").notNull(), baseScopeId: text("base_scope_id").notNull().references(() => scopes.id), request: text("request").notNull(), analysis: jsonb("analysis").$type<Comparison>(), review: jsonb("review").$type<Comparison>(), status: text("status", { enum: ["DRAFT", "WAITING_INTERNAL_REVIEW", "WAITING_CLIENT_APPROVAL", "APPROVED", "REJECTED", "CANCELLED"] }).notNull().default("DRAFT"), rates: jsonb("rates").$type<Rates>().notNull(), amount: doublePrecision("amount").notNull().default(0), adjustmentReason: text("adjustment_reason").notNull().default(""), reviewedBy: text("reviewed_by"), resultScopeId: text("result_scope_id").references(() => scopes.id), approvedAt: timestamp("approved_at", { withTimezone: true }), approvedBy: text("approved_by"), revision: integer("revision").notNull().default(0), createdAt: created() }, t => [uniqueIndex("change_project_number_unique").on(t.projectId, t.number)]);
export const accessTokens = pgTable("client_access_tokens", { id: pk(), projectId: text("project_id").notNull().references(() => projects.id), scopeId: text("scope_id").references(() => scopes.id), changeId: text("change_id").references(() => changes.id), purpose: text("purpose", { enum: ["QUESTIONS", "SCOPE", "CHANGE"] }).notNull(), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), revokedAt: timestamp("revoked_at", { withTimezone: true }), createdAt: created() }, t => [check("token_document_target", sql`(${t.purpose} = 'QUESTIONS' AND ${t.scopeId} IS NULL AND ${t.changeId} IS NULL) OR (${t.purpose} = 'SCOPE' AND ${t.scopeId} IS NOT NULL AND ${t.changeId} IS NULL) OR (${t.purpose} = 'CHANGE' AND ${t.changeId} IS NOT NULL AND ${t.scopeId} IS NULL)`)]);
export const feedback = pgTable("client_feedback", { id: pk(), projectId: text("project_id").notNull().references(() => projects.id), tokenId: text("token_id").notNull().references(() => accessTokens.id), decision: text("decision").notNull(), name: text("name").notNull(), message: text("message").notNull(), createdAt: created() });
export const aiUsage = pgTable("ai_usage", { id: pk(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), userId: text("user_id").notNull().references(() => user.id), projectId: text("project_id").notNull().references(() => projects.id), action: text("action").notNull(), model: text("model").notNull(), promptVersion: text("prompt_version").notNull(), inputTokens: integer("input_tokens").notNull().default(0), outputTokens: integer("output_tokens").notNull().default(0), cachedTokens: integer("cached_tokens").notNull().default(0), estimatedCost: doublePrecision("estimated_cost").notNull().default(0), creditsUsed: integer("credits_used").notNull(), status: text("status").notNull().default("PENDING"), createdAt: created() }, t => [index("usage_workspace_month_idx").on(t.workspaceId, t.createdAt), index("usage_user_month_idx").on(t.userId, t.createdAt)]);
export const aiCache = pgTable("ai_result_cache", { id: pk(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), hash: text("hash").notNull(), result: jsonb("result").$type<unknown>(), leaseUntil: timestamp("lease_until", { withTimezone: true }).notNull(), createdAt: created() }, t => [uniqueIndex("cache_workspace_hash_unique").on(t.workspaceId, t.hash)]);
export const aiDrafts = pgTable("ai_drafts", { id: pk(), projectId: text("project_id").notNull().references(() => projects.id), action: text("action").notNull(), result: jsonb("result").$type<unknown>().notNull(), revision: integer("revision").notNull(), appliedAt: timestamp("applied_at", { withTimezone: true }), createdAt: created() }, t => [uniqueIndex("draft_project_action_unique").on(t.projectId, t.action)]);
export const requestLimits = pgTable("request_limits", { key: text("key").primaryKey(), count: integer("count").notNull(), resetAt: timestamp("reset_at", { withTimezone: true }).notNull() });
export const auditLogs = pgTable("audit_logs", { id: pk(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), projectId: text("project_id").references(() => projects.id), actor: text("actor").notNull(), event: text("event").notNull(), detail: text("detail").notNull(), createdAt: created() }, t => [index("audit_workspace_created_idx").on(t.workspaceId, t.createdAt)]);
